/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author llima
 */
public class FormNedocs extends javax.swing.JFrame {

    /**
     * Creates new form FromNedocs
     */
    public FormNedocs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFormNedocsBotao = new javax.swing.JPanel();
        jButtonQuando = new javax.swing.JButton();
        jButtonObservacoes = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabelNedocs = new javax.swing.JLabel();
        jLabelDescricaoNedocs = new javax.swing.JLabel();
        jPanelFormNedocsdados = new javax.swing.JPanel();
        jLabelNumeroCamas = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jButtonNedocsCalcular = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanelNedocsDataHora = new javax.swing.JPanel();
        jLabelNedocsData = new javax.swing.JLabel();
        jTextFieldNedocsData = new javax.swing.JTextField();
        jLabelNedocsHora = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButtonFormNedocsSalvar = new javax.swing.JButton();
        jButtonFormNedocsExcluir = new javax.swing.JButton();
        jButtonFormNedocsProdcurar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanelFormNedocsBotao.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonQuando.setText("Quando utilizar?");
        jButtonQuando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuandoActionPerformed(evt);
            }
        });

        jButtonObservacoes.setText("Observações Gerais");

        jButton1.setText("Por que utilizar?");

        javax.swing.GroupLayout jPanelFormNedocsBotaoLayout = new javax.swing.GroupLayout(jPanelFormNedocsBotao);
        jPanelFormNedocsBotao.setLayout(jPanelFormNedocsBotaoLayout);
        jPanelFormNedocsBotaoLayout.setHorizontalGroup(
            jPanelFormNedocsBotaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormNedocsBotaoLayout.createSequentialGroup()
                .addComponent(jButtonQuando)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonObservacoes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(327, Short.MAX_VALUE))
        );
        jPanelFormNedocsBotaoLayout.setVerticalGroup(
            jPanelFormNedocsBotaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormNedocsBotaoLayout.createSequentialGroup()
                .addGroup(jPanelFormNedocsBotaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonQuando)
                    .addComponent(jButtonObservacoes)
                    .addComponent(jButton1))
                .addGap(13, 13, 13))
        );

        getContentPane().add(jPanelFormNedocsBotao);
        jPanelFormNedocsBotao.setBounds(30, 60, 690, 40);

        jLabelNedocs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelNedocs.setText("NEDOCS - Escala para avaliação da superlotação dos serviços de emergência");
        getContentPane().add(jLabelNedocs);
        jLabelNedocs.setBounds(30, 10, 490, 15);

        jLabelDescricaoNedocs.setText(" Estima a gravidade da superlotação nos departamentos de emergência");
        getContentPane().add(jLabelDescricaoNedocs);
        jLabelDescricaoNedocs.setBounds(32, 32, 500, 14);

        jPanelFormNedocsdados.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelNumeroCamas.setText("Número total de pacientes em atendimento");
        jLabelNumeroCamas.setToolTipText("O número total de pacientes em atendimento no Serviço de Emergência, erm qualquer tipo de acomodação.");

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setToolTipText("O número total de pacientes em atendimento no Serviço de Emergência, erm qualquer tipo de acomodação.");
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel1.setText("Acomodações no serviço de emergência (formais e informais)");
        jLabel1.setToolTipText("Número total de acomodações formais e informais no Serviço de Emergência incluindo macas, poltronas, cadeiras e camas, ou seja, todas as acomodações onde os pacientes podeme/ou estão sendo atendidos.");

        jLabel2.setText("Total de pacientes com prescrição de internação no Serviço de Emergência");
        jLabel2.setToolTipText("O número total de pacientes com prescrição de internação que permanecem em acomodações (formais e informais) no Serviço de Emergência, aguardando leito para trasferência.");

        jLabel3.setText("Número de leitos (oficiais) do hospital destinados ao Serviço de Emergência");
        jLabel3.setToolTipText("O número de leitos (oficiais) do hospital destinados ao Serviço de Emergência, disquinguindo leitos adultos e pediátricos.");

        jLabel4.setText("Pacientes em ventilação");
        jLabel4.setToolTipText("O número de pacientes em ventilação invasiva/não invasiva no Serviço de Emergência no momento da colata da informação.");

        jLabel5.setText("Maior tempo de permanência de um paciente com prescrição de internação no S. E.");
        jLabel5.setToolTipText("O maior tempo de permanência (em horas) de um paciente no Serviço de Emergência com prescrição de internação, até o momento em que a escala é aplicada.");

        jLabel6.setText("Tempo de espera aguardado pelo último paciente de maior risco, para o primeiro atendimento médico");
        jLabel6.setToolTipText("O tempo de espera (em horas_ aguardado pelo último paciente de maior risco até o primeiro atendimento médico, no momento em que a escala é aplicada.");

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField2.setToolTipText("Acomodações no serviço de emergência (formais e informais)");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField3.setToolTipText("O número total de pacientes com prescrição de internação que permanecem em acomodações (formais e informais) no Serviço de Emergência, aguardando leito para trasferência.");

        jTextField4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField4.setToolTipText("O número de leitos (oficiais) do hospital destinados ao Serviço de Emergência, disquinguindo leitos adultos e pediátricos");

        jTextField5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField5.setToolTipText("O número de pacientes em ventilação invasiva/não invasiva no Serviço de Emergência no momento da colata da informação.");

        jTextField6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField6.setToolTipText("O maior tempo de permanência (em horas) de um paciente no Serviço de Emergência com prescrição de internação, até o momento em que a escala é aplicada.");

        jTextField7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField7.setToolTipText("O tempo de espera (em horas_ aguardado pelo último paciente de maior risco até o primeiro atendimento médico, no momento em que a escala é aplicada.");

        jButtonNedocsCalcular.setText("Calcular e salvar");
        jButtonNedocsCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNedocsCalcularActionPerformed(evt);
            }
        });

        jButton2.setText("Novo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFormNedocsdadosLayout = new javax.swing.GroupLayout(jPanelFormNedocsdados);
        jPanelFormNedocsdados.setLayout(jPanelFormNedocsdadosLayout);
        jPanelFormNedocsdadosLayout.setHorizontalGroup(
            jPanelFormNedocsdadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormNedocsdadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFormNedocsdadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFormNedocsdadosLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                    .addGroup(jPanelFormNedocsdadosLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField6))
                    .addGroup(jPanelFormNedocsdadosLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5))
                    .addGroup(jPanelFormNedocsdadosLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4))
                    .addGroup(jPanelFormNedocsdadosLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3))
                    .addGroup(jPanelFormNedocsdadosLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2))
                    .addGroup(jPanelFormNedocsdadosLayout.createSequentialGroup()
                        .addComponent(jLabelNumeroCamas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1))
                    .addGroup(jPanelFormNedocsdadosLayout.createSequentialGroup()
                        .addComponent(jButtonNedocsCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelFormNedocsdadosLayout.setVerticalGroup(
            jPanelFormNedocsdadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFormNedocsdadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFormNedocsdadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumeroCamas)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelFormNedocsdadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanelFormNedocsdadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanelFormNedocsdadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelFormNedocsdadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelFormNedocsdadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelFormNedocsdadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelFormNedocsdadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNedocsCalcular)
                    .addComponent(jButton2))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        jTextField1.getAccessibleContext().setAccessibleName("");

        getContentPane().add(jPanelFormNedocsdados);
        jPanelFormNedocsdados.setBounds(30, 230, 690, 400);

        jPanelNedocsDataHora.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelNedocsData.setText("Data:");

        jTextFieldNedocsData.setToolTipText("Data - formato: DD/MM/YYYY");

        jLabelNedocsHora.setText("Hora:");

        jTextField8.setToolTipText("Hora no formato (HH:MI)");

        jLabel7.setText("Instituição: ");

        jTextField9.setEditable(false);
        jTextField9.setBackground(new java.awt.Color(204, 204, 204));
        jTextField9.setText("UPA Rio das Ostras");

        jLabel8.setText("Código:");

        jTextField10.setEditable(false);
        jTextField10.setBackground(new java.awt.Color(204, 204, 204));
        jTextField10.setText("210");

        jLabel9.setText("Usuário:");

        jTextField11.setEditable(false);
        jTextField11.setBackground(new java.awt.Color(204, 204, 204));
        jTextField11.setText("Leonardo Bruno Lima");

        javax.swing.GroupLayout jPanelNedocsDataHoraLayout = new javax.swing.GroupLayout(jPanelNedocsDataHora);
        jPanelNedocsDataHora.setLayout(jPanelNedocsDataHoraLayout);
        jPanelNedocsDataHoraLayout.setHorizontalGroup(
            jPanelNedocsDataHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNedocsDataHoraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelNedocsDataHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelNedocsDataHoraLayout.createSequentialGroup()
                        .addGroup(jPanelNedocsDataHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNedocsData, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNedocsData))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelNedocsDataHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNedocsHora)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelNedocsDataHoraLayout.createSequentialGroup()
                        .addGroup(jPanelNedocsDataHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelNedocsDataHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelNedocsDataHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelNedocsDataHoraLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextField11, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanelNedocsDataHoraLayout.setVerticalGroup(
            jPanelNedocsDataHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNedocsDataHoraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelNedocsDataHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelNedocsDataHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanelNedocsDataHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNedocsData)
                    .addComponent(jLabelNedocsHora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelNedocsDataHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNedocsData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelNedocsDataHora);
        jPanelNedocsDataHora.setBounds(30, 100, 690, 120);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonFormNedocsSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvar.png"))); // NOI18N
        jButtonFormNedocsSalvar.setToolTipText("Salvar");
        jButtonFormNedocsSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFormNedocsSalvarActionPerformed(evt);
            }
        });

        jButtonFormNedocsExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir.png"))); // NOI18N
        jButtonFormNedocsExcluir.setToolTipText("Excluir");

        jButtonFormNedocsProdcurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/procurar.png"))); // NOI18N
        jButtonFormNedocsProdcurar.setToolTipText("Procurar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonFormNedocsSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButtonFormNedocsProdcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButtonFormNedocsExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonFormNedocsProdcurar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jButtonFormNedocsExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jButtonFormNedocsSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(610, 0, 110, 50);

        setSize(new java.awt.Dimension(751, 693));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNedocsCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNedocsCalcularActionPerformed
    ResultadoNedocs Tela = new ResultadoNedocs();
    Tela.setVisible(true);
        


// TODO add your handling code here:
    }//GEN-LAST:event_jButtonNedocsCalcularActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButtonQuandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuandoActionPerformed
NedocsQuandoUtilizar Tela = new NedocsQuandoUtilizar();
Tela.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButtonQuandoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonFormNedocsSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFormNedocsSalvarActionPerformed
ResultadoNedocs Tela = new ResultadoNedocs();
    Tela.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFormNedocsSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormNedocs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormNedocs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormNedocs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormNedocs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormNedocs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonFormNedocsExcluir;
    private javax.swing.JButton jButtonFormNedocsProdcurar;
    private javax.swing.JButton jButtonFormNedocsSalvar;
    private javax.swing.JButton jButtonNedocsCalcular;
    private javax.swing.JButton jButtonObservacoes;
    private javax.swing.JButton jButtonQuando;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDescricaoNedocs;
    private javax.swing.JLabel jLabelNedocs;
    private javax.swing.JLabel jLabelNedocsData;
    private javax.swing.JLabel jLabelNedocsHora;
    private javax.swing.JLabel jLabelNumeroCamas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelFormNedocsBotao;
    private javax.swing.JPanel jPanelFormNedocsdados;
    private javax.swing.JPanel jPanelNedocsDataHora;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jTextFieldNedocsData;
    // End of variables declaration//GEN-END:variables
}
