/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.UsuarioDAO;
import java.awt.Toolkit;
import java.security.InvalidAlgorithmParameterException;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.BadPaddingException;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;
import javax.swing.JOptionPane;
import modelo.Usuario;
import util.SenhaBanco;
import util.config;

/**
 *
 * @author llima
 */
public class TelaLogin extends javax.swing.JFrame {

    public static String logado;
    public static String versao;

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        //Colocando Título na Tela
        this.setTitle(new config().getTitulo());
        //setando icone
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("imagens\\icon.png"));
        jPanelAlteraSenha.setVisible(false);
        jPanelLogon.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLogon = new javax.swing.JPanel();
        jButtonAcessar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jTextFieldUsuario = new javax.swing.JTextField();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelSenha = new javax.swing.JLabel();
        jPanelAlteraSenha = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPasswordFieldSenhaNova = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jPasswordFieldRepeticao = new javax.swing.JPasswordField();
        jButtonAlterarSenha = new javax.swing.JButton();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanelLogon.setBackground(new java.awt.Color(255, 255, 255));

        jButtonAcessar.setText("Acessar");
        jButtonAcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcessarActionPerformed(evt);
            }
        });

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jPasswordFieldSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordFieldSenhaKeyPressed(evt);
            }
        });

        jTextFieldUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldUsuarioKeyPressed(evt);
            }
        });

        jLabelUsuario.setText("Usuário: ");

        jLabelSenha.setText("Senha:");

        javax.swing.GroupLayout jPanelLogonLayout = new javax.swing.GroupLayout(jPanelLogon);
        jPanelLogon.setLayout(jPanelLogonLayout);
        jPanelLogonLayout.setHorizontalGroup(
            jPanelLogonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLogonLayout.createSequentialGroup()
                .addGroup(jPanelLogonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLogonLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jButtonAcessar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSair))
                    .addGroup(jPanelLogonLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelLogonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelUsuario)
                            .addComponent(jLabelSenha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLogonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPasswordFieldSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                            .addComponent(jTextFieldUsuario))))
                .addGap(20, 20, 20))
        );
        jPanelLogonLayout.setVerticalGroup(
            jPanelLogonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLogonLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelLogonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUsuario)
                    .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLogonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addGroup(jPanelLogonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAcessar)
                    .addComponent(jButtonSair))
                .addGap(23, 23, 23))
        );

        getContentPane().add(jPanelLogon);
        jPanelLogon.setBounds(410, 210, 280, 140);

        jPanelAlteraSenha.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Senha Nova:");

        jPasswordFieldSenhaNova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldSenhaNovaActionPerformed(evt);
            }
        });
        jPasswordFieldSenhaNova.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordFieldSenhaNovaKeyPressed(evt);
            }
        });

        jLabel2.setText("Repita:");

        jPasswordFieldRepeticao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordFieldRepeticaoKeyPressed(evt);
            }
        });

        jButtonAlterarSenha.setText("Alterar Senha");
        jButtonAlterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarSenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAlteraSenhaLayout = new javax.swing.GroupLayout(jPanelAlteraSenha);
        jPanelAlteraSenha.setLayout(jPanelAlteraSenhaLayout);
        jPanelAlteraSenhaLayout.setHorizontalGroup(
            jPanelAlteraSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlteraSenhaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPasswordFieldSenhaNova, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelAlteraSenhaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPasswordFieldRepeticao, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelAlteraSenhaLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jButtonAlterarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelAlteraSenhaLayout.setVerticalGroup(
            jPanelAlteraSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlteraSenhaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelAlteraSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jPasswordFieldSenhaNova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanelAlteraSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordFieldRepeticao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAlterarSenha)
                .addContainerGap())
        );

        getContentPane().add(jPanelAlteraSenha);
        jPanelAlteraSenha.setBounds(410, 210, 280, 140);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/FundoImagem.jpg"))); // NOI18N
        getContentPane().add(jLabelFundo);
        jLabelFundo.setBounds(0, 0, 867, 840);

        setSize(new java.awt.Dimension(769, 414));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcessarActionPerformed
        Usuario u = new Usuario();
        UsuarioDAO udao = new UsuarioDAO();
        String usuario = jTextFieldUsuario.getText();
        String senhaDigitada = jPasswordFieldSenha.getText();
        String senhaBanco = null;
        String senhaDigitadaCriptografada = null;
        try {
            senhaBanco = udao.buscaSenha(usuario);
        } catch (BadPaddingException ex) {
            Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchPaddingException ex) {
            Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalBlockSizeException ex) {
            Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvalidKeyException ex) {
            Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvalidAlgorithmParameterException ex) {
            Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            //Descriptografando senha do Banco
            senhaDigitadaCriptografada = SenhaBanco.encrypt(senhaDigitada);
        } catch (BadPaddingException ex) {
            Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchPaddingException ex) {
            Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalBlockSizeException ex) {
            Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvalidKeyException ex) {
            Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvalidAlgorithmParameterException ex) {
            Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
        }

        //Conferindo se Senha Digitada confere com o banco de dados
        if (senhaDigitadaCriptografada == null ? senhaBanco == null : senhaDigitadaCriptografada.equals(senhaBanco)) {
            boolean provisorio = false;
            try {
                provisorio = udao.checaSenhaProvisoria(usuario);
            } catch (BadPaddingException ex) {
                Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NoSuchPaddingException ex) {
                Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalBlockSizeException ex) {
                Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InvalidKeyException ex) {
                Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NoSuchAlgorithmException ex) {
                Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InvalidAlgorithmParameterException ex) {
                Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (provisorio) {
                JOptionPane.showMessageDialog(rootPane, "Senha expirada! Favor alterá-la.");
                jPanelAlteraSenha.setVisible(true);
                jPanelLogon.setVisible(false);
                jPasswordFieldSenhaNova.requestFocus();
            } else {
                TelaPrincipal tela = new TelaPrincipal();
                tela.setVisible(true);
                dispose();
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Usuário e/ou Senha inválidos!");
            jPasswordFieldSenha.setText(null);
            jPasswordFieldSenha.requestFocus();
        }

// TODO add your handling code here:
    }//GEN-LAST:event_jButtonAcessarActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        System.exit(0);       // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jPasswordFieldSenhaNovaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldSenhaNovaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            jPasswordFieldRepeticao.requestFocus();
        }
    }//GEN-LAST:event_jPasswordFieldSenhaNovaKeyPressed

    private void jPasswordFieldRepeticaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldRepeticaoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            jButtonAlterarSenha.doClick();
        }
    }//GEN-LAST:event_jPasswordFieldRepeticaoKeyPressed

    private void jButtonAlterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarSenhaActionPerformed
        // TODO add your handling code here:
        String usuario = jTextFieldUsuario.getText();
        String senhaNova = jPasswordFieldSenhaNova.getText();
        String repeticao = jPasswordFieldRepeticao.getText();
        if(senhaNova == null ? repeticao == null : senhaNova.equals(repeticao)) {
            UsuarioDAO udao = new UsuarioDAO();
            boolean sucesso = false;
            try {
                sucesso = udao.atualizaSenha(usuario, senhaNova);
            } catch (BadPaddingException ex) {
                Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NoSuchPaddingException ex) {
                Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalBlockSizeException ex) {
                Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InvalidKeyException ex) {
                Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NoSuchAlgorithmException ex) {
                Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InvalidAlgorithmParameterException ex) {
                Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (sucesso){
                JOptionPane.showMessageDialog(rootPane, "Senha alterada com sucesso!");
                jPanelAlteraSenha.setVisible(false);
                jPasswordFieldSenha.setText(null);
                jPanelLogon.setVisible(true);
                jPasswordFieldSenha.requestFocus();
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Senhas não conferem!");
        }
    }//GEN-LAST:event_jButtonAlterarSenhaActionPerformed

    private void jTextFieldUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            jPasswordFieldSenha.requestFocus();
        }
    }//GEN-LAST:event_jTextFieldUsuarioKeyPressed

    private void jPasswordFieldSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldSenhaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            jButtonAcessar.doClick();
        }
    }//GEN-LAST:event_jPasswordFieldSenhaKeyPressed

    private void jPasswordFieldSenhaNovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldSenhaNovaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldSenhaNovaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAcessar;
    private javax.swing.JButton jButtonAlterarSenha;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanelAlteraSenha;
    private javax.swing.JPanel jPanelLogon;
    private javax.swing.JPasswordField jPasswordFieldRepeticao;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JPasswordField jPasswordFieldSenhaNova;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
